import numpy as np
import matplotlib.pyplot as plt
# print(arr2.ndim)
# print(type(arr))
# print(arr2.shape[0], arr2.shape[1], arr2.shape[2])
# print(arr2[0, 1, 2])
# a = np.arange(1, 101, 2).reshape(5, 10)
# a = np.random.rand(100000)
# plt.hist(a, bins=200)
# plt.show()

a = np.zeros((4, 2))
# a = np.ones(10)
# arr = np.arange(10)
# print(arr)
# a = np.random.permutation(arr)
# print(arr3[1:])
# print(arr3[::-1])
# print(arr3[1:5])
# print(arr3[:: 2])
# arr = np.array([[1, 23, 4], [3, 5, 6]], dtype='int16')
# arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
# arr3 = np.array([1, 2, 3, 4, 5, 9])
# arr = np.arange(100).reshape(10, 10)

# b = arr[2::3, 3::2].copy()
# print(b)
# idx = np.argwhere(b == 89)
# print(idx[0])
# print(b[idx[0][0]][idx[0][1]])
# arr = np.random.rand(10)
# print(arr)
# a = np.round(10*arr).reshape(2, 5)
# print(a)

# arr = np.arange(100).reshape(10, 10)
# print(arr)
# print(arr.T)
# print(np.transpose(arr))
# print(a)
# a.sort(axis=1)
# print(a)

# arr = np.random.randint(0, 50, size=(5, 10))
# b = arr[(arr < 40) & (arr > 30)]
# c = arr[(arr < 20) | (arr > 40)]
# print(arr)
# print(b)
# print(c)

# arr = np.arange(10).reshape((5, 2))
# arr2 = np.arange(10, 20).reshape((5, 2))
# a = np.hstack((arr, arr2))
# b = np.vstack((arr, arr2))
# print(a)
# print('========')
# print(b)

arr = np.arange(100000)
print(np.sum(arr))
